
CREATE TABLE IF NOT EXISTS atributos (
    atributo TEXT PRIMARY KEY,
    perfil TEXT,
    categoria TEXT,
    area_suporte TEXT
);

DELETE FROM atributos;
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ACABATIVO', 'Resultado', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ACOMODADO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ADAPTÁVEL', 'Influenciador', 'Versátil', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ADICÇÕES', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AGRESSIVIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ALTA SENSIBILIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ALTRUÍSTA', NULL, 'Justo', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AMOROSIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ANÁLISE', NULL, 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ANÁLISE MENTAL', NULL, 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ANALISTA', NULL, 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ANTI SOCIAL', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ARROGÂNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ARTISTA', NULL, 'Comunicativo', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AUDÁCIA', 'Lider', 'Inovador', 'Versatilidade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AUTO CONFIANÇA', 'Lider', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AUTO EXPRESSÃO', 'Comunicador', 'Comunicativo', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AVAREZA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CARISMA', 'Influenciador', 'Magnético', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CENTRALIZADOR', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('COLABORAÇÃO', NULL, 'Empático', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('COLETIVO', 'Lider', NULL, 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('COMUNICAÇÃO', 'Comunicador', 'Comunicativo', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONCRETIZAÇÃO', 'Resultado', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONEXÃO', 'Influenciador', 'Versátil', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONFIANÇA', 'Lider', 'Realizador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONHECIMENTO', 'Lider', 'Conhecimento', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONQUISTA', 'Vendedor', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONSCIÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONSELHEIRO', 'Influenciador', 'Diplomático', 'Justiça');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONSTÂNCIA', 'Executor', 'Realizador', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONSTRUTOR', 'Executor', 'Realizador', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CONVICÇÃO', NULL, 'Intuitivo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('COOPERAÇÃO', NULL, NULL, 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CORAGEM', 'Lider', NULL, 'Justiça');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CRIATIVO', 'Criativo', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DESCONFIANÇA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DESCONTROLE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DESINTERESSE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DESPREOCUPAÇÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DETALHISTA', NULL, 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DETERMINAÇÃO', 'Lider', 'Realizador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DINHEIRO', 'Vendedor', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DIPLOMACIA', NULL, 'Diplomático', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DIRECIONAMENTO', 'Lider', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DOMINADOR', 'Influenciador', 'Magnético', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('DOMINÂNCIA', 'Lider', 'Intuitivo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EGOCENTRISMO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EMPATIA', NULL, 'Empático', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EMPREENDEDOR', 'Resultado', 'Realizador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ENTUSIASMO', 'Comunicador', 'Comunicativo', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EQUIPE', 'Lider', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ESPECIALISTA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ESPERANÇA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ESTABILIDADE', 'Resultado', 'Organizado', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EXECUTOR', 'Executor', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EXIBICIONISMO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ÊXITO MATERIAL', 'Vendedor', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EXPLOSÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('EXTREMISTA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('FALTA DE CREDIBILIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('FALTA DE PERSISTÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('FALTA DE VONTADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('FECHADO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CRIAÇÃO', 'Criativo', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('GANÂNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('HABILIDADE', NULL, 'Diplomático', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('HARMONIA', NULL, 'Harmônico', 'Serviço');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('IMPACIÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('IMPACIENTE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('IMPOSITIVO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INCONSEQUENTE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INCONSISTÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INDECISÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INDISCIPLINA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INDOLÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INFLUENCIADOR', 'Influenciador', 'Magnético', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INICIATIVA', 'Lider', 'Inovador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INOVAÇÃO', 'Criativo', 'Inovador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INSEGURANÇA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INSPIRAÇÃO', 'Criativo', 'Intuitivo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INSTABILIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INSUBORDINAÇÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INTELECTUALIDADE', NULL, 'Conhecimento', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('INTUITIVO', 'Criativo', 'Intuitivo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('JUSTIÇA', NULL, 'Justo', 'Justiça');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('LIDER', 'Lider', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('MAGNETISMO PESSOAL', 'Influenciador', 'Magnético', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('MENTIRA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('MOVIMENTAÇÃO', 'Vendedor', 'Versátil', 'Versatilidade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('MULTITALENTO', 'Comunicador', 'Versátil', 'Versatilidade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ORGANIZAÇÃO', 'Executor', 'Organizado', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('ORGULHO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PERÍCIA', NULL, 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PERSISTÊNCIA', 'Executor', 'Realizador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PERSPICÁCIA', 'Executor', 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PERSUASÃO', 'Influenciador', 'Comunicativo', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PESSIMISMO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PIONEIRO', 'Lider', 'Inovador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PIONIERISMO', 'Lider', 'Inovador', NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('AUTORIDADE', NULL, 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PODER', 'Lider', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PODER MENTAL', 'Influenciador', 'Comunicativo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('POPULAR', 'Influenciador', 'Magnético', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PREOCUPAÇÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PREPOTÊNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PRESUNÇÃO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('PROGRESSO', 'Executor', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('REALIZAÇÃO', 'Executor', 'Realizador', 'Execução');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('RELACIONAMENTO', NULL, NULL, 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('RENUNCIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('RESPONSABILIDADE', 'Executor', 'Realizador', 'Disciplina');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('RESULTADO', 'Resultado', 'Realizador', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SABEDORIA', 'Influenciador', 'Intuitivo', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SELETIVO', 'Executor', 'Analítico', 'Análise');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SEM LIMITES', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SENSÍVEL', NULL, 'Harmônico', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('CENSURA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SENTIMENTAL', NULL, NULL, 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SERVIÇO', 'Executor', 'Realizador', 'Serviço');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SERVIDOR', 'Executor', 'Conhecimento', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SOCIABILIDADE', 'Comunicador', 'Comunicativo', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SOCIAL', 'Influenciador', 'Diplomático', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SOLÍCITO', 'Executor', 'Harmônico', 'Relacionamento');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SUCESSO', 'Influenciador', 'Visionário', 'Comunicação');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('SUPERIORIDADE', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('TEIMOSIA', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('TENSO', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('TODOS', NULL, NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('TRIUNFO', 'Resultado', 'Realizador', 'Organização');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('UNIVERSALIDADE', NULL, 'Conhecimento', 'Coletividade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('VENDEDOR', 'Vendedor', NULL, NULL);
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('VERSATILIDADE', 'Comunicador', 'Versátil', 'Versatilidade');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('VISIONÁRIO', NULL, 'Visionário', 'Intuição');
INSERT INTO atributos (atributo, perfil, categoria, area_suporte) VALUES ('VONTADE', NULL, 'Realizador', NULL);
