
CREATE TABLE IF NOT EXISTS categoria_descricao (
    id SERIAL PRIMARY KEY,
    categoria TEXT,
    descricao TEXT
);

INSERT INTO categoria_descricao (categoria, descricao) VALUES
('Magnético', 'Extrovertido, comunicação fácil e rápida. Expressa-se de diversas formas e tem muitas ideias. Carismático, alegre, criativo. Raciocínio rápido, aprende com facilidade e se comunica com articulação. Capacidade de atração e magnetismo. Positivista, otimista e sociável, comunica-se com todas as pessoas. Expressa assuntos densos com um tom extrovertido, sem pesar o ambiente. Representa novas idéias, curiosidade. Ousado, inquieto, adaptável, gostando de novas perspectivas e movimento. Possui mente ágil, absorve e aprende com as experiências vividas. Gosta de atividades sociais, de viagens. Flexível, concilia várias atividades ao mesmo tempo.'),
('Prático', 'Lógico, simples, organizado, honesto, prático e conservador. Está ligado ao método, a solidez, é sistemático e disciplinado. Paciente e cauteloso, transmite estabilidade e confiança. Trabalhador e eficiente, procura por estabilidade e conhece o valor do compromisso firmado. Ótimo conselheiro, fiel, esforça-se para ajudar e resolver as tarefas.'),
('Analítico', 'Bem informado, receptivo, individual, seletivo, criterioso e lógico. Sente-se muito bem em ambientes fechados, absorvendo conhecimento. Grande capacidade de análise, pensamento lógico, equilíbrio mental e ações cautelosas. Estudioso, pensador, absorve conhecimentos e é autônomo nas decisões. Capaz de extrair percepções a partir dos dados. Adquire conhecimento para a tomada de decisão.'),
('Organizado', 'Lógico, simples, organizado, prático, ordeiro. Está ligado ao método, a solidez; é sistemático e disciplinado. Paciente e cauteloso, transmite estabilidade e confiança. Procura por uma carreira estável e valoriza o compromisso firmado. Ótimo conselheiro, empenhado em ajudar nas tarefas.'),
('Financeiro', 'Observador, conservador e sabe, intuitivamente, superar os obstáculos para chegar ao sucesso dos seus objetivos. Tem temperamento mais frio e calculista, para enfrentar crises, sem alarde ou desespero. Ambicioso e justo. Tem metas definidas e não se deixa perturbar até que conclua suas metas.'),
('Acabativo', 'Construtor, intuitivo, ousado, seu desejo é realizar e concretizar o que estiver em suas mãos. Possui domínio, poder, sensibilidade, expansão. Eficiente, capaz de ser prático e concretizador, pois é altamente produtivo. Tem sucesso em atividades que sejam construídas em bases sólidas. Construtor com ideais amplos, habilidade diplomática e poder. Sua prioridade é voltada para as concretizações materiais, acordos, parcerias de negócios, tendo em vista sempre algo voltado ao sucesso.'),
('Comunicativo', 'Facilidade em expressar suas ideias, pensamentos e sentimentos. É aberto ao diálogo, gosta de interagir com os outros e têm habilidades sociais desenvolvidas. Capaz de transmitir informações de maneira eficaz, adaptando seu estilo de comunicação conforme a situação e o público.'),
('Intuitivo', 'Destaca-se pela capacidade de processar informações complexas de forma rápida e subconsciente, utilizando experiências e padrões acumulados para tomar decisões assertivas em situações de incerteza. No ambiente de trabalho, essa característica não substitui a lógica, mas a complementa, permitindo uma visão estratégica e antecipatória.'),
('Harmônico', 'Palavra de ordem: colaboração. Sempre interessado em fazer parcerias, tem um estilo persuasivo ligado à gentileza; Não sente a necessidade de aparecer para o público, opera nos bastidores, como coadjuvante, mas com independência, liderança, comando com firmeza e originalidade. Suas ações são simétricas, harmoniosas. Tem uma atuação bem exercida através da conciliação e pacificação. Se importa muito com a cooperação, diplomacia, tato, política, amabilidade. Seu perfil é mais introvertido. É um pacificador e ótimo colaborador, realizando suas metas sem reclamar dos obstáculos, não gostando muito de ficar em evidência. Receptivo, sensível e paciente. É um ótimo mediador para situações, pessoas e negócios.'),
('Conhecimento', 'Prudente, com processos burocráticos. Busca as realizações independente do tempo que leve para conseguir. Tem consciência sobre o que realiza. Não gosta de perder tempo com preocupações rotineiras.');
