CREATE TABLE IF NOT EXISTS mapas_salvos_valores (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT UNIQUE NOT NULL,
    data_nascimento TEXT,
    kan TEXT,
    perfil TEXT,
    categoria TEXT,
    qualidades TEXT,
    diferenciais TEXT,
    motivacao TEXT,
    impressao TEXT,
    expressao TEXT,
    dia_natalicio TEXT,
    numero_psiquico TEXT,
    destino TEXT,
    missao TEXT,
    direcionamento TEXT,
    estrutural TEXT,
    repeticao_1 TEXT,
    repeticao_2 TEXT,
    repeticao_mapa TEXT,
    repeticao_mapa_2 TEXT,
    vertice_triangulo_1 TEXT,
    vertice_triangulo_2 TEXT,
    vertice_triangulo_3 TEXT,
    dividas_carmicas TEXT,
    licoes_carmicas TEXT,
    tendencias_ocultas TEXT,
    resposta_subconsciente TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Habilita RLS por padrão para proteger os dados (Apenas service_role terá acesso se nenhuma política for definida)
ALTER TABLE mapas_salvos_valores ENABLE ROW LEVEL SECURITY;

-- Permite que usuários autenticados visualizem/manipulem mapas_salvos_valores apenas se tiverem acesso ao talento correspondente em mapas_salvos
DROP POLICY IF EXISTS "tenant_isolation_mapas_valores" ON mapas_salvos_valores;
CREATE POLICY "tenant_isolation_mapas_valores" ON mapas_salvos_valores
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.mapas_salvos
            WHERE public.mapas_salvos.nome = public.mapas_salvos_valores.nome
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.mapas_salvos
            WHERE public.mapas_salvos.nome = public.mapas_salvos_valores.nome
        )
    );
