-- Script de definição de tabela para Fórmulas Numerológicas Salvas no Supabase

CREATE TABLE IF NOT EXISTS formulas_numerologicas_salvas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    estrutura JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilita Row Level Security (RLS) na tabela
ALTER TABLE formulas_numerologicas_salvas ENABLE ROW LEVEL SECURITY;

-- Cria políticas de acesso público (Leitura, Inserção, Atualização e Exclusão)
CREATE POLICY "Permitir leitura pública de fórmulas" 
ON formulas_numerologicas_salvas FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserção pública de fórmulas" 
ON formulas_numerologicas_salvas FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir atualização pública de fórmulas" 
ON formulas_numerologicas_salvas FOR UPDATE 
USING (true);

CREATE POLICY "Permitir exclusão pública de fórmulas" 
ON formulas_numerologicas_salvas FOR DELETE 
USING (true);
