CREATE TABLE IF NOT EXISTS mapas_salvos_valores (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT UNIQUE NOT NULL,
    data_nascimento TEXT,
    kan TEXT,
    perfil TEXT,
    categoria TEXT,
    qualidades TEXT,
    diferenciais TEXT,
    motivacao TEXT,
    impressao TEXT,
    expressao TEXT,
    dia_natalicio TEXT,
    numero_psiquico TEXT,
    destino TEXT,
    missao TEXT,
    direcionamento TEXT,
    estrutural TEXT,
    repeticao_1 TEXT,
    repeticao_2 TEXT,
    repeticao_mapa TEXT,
    repeticao_mapa_2 TEXT,
    vertice_triangulo_1 TEXT,
    vertice_triangulo_2 TEXT,
    vertice_triangulo_3 TEXT,
    dividas_carmicas TEXT,
    licoes_carmicas TEXT,
    tendencias_ocultas TEXT,
    resposta_subconsciente TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Habilita RLS por padrão para proteger os dados (Apenas service_role terá acesso)
ALTER TABLE mapas_salvos_valores ENABLE ROW LEVEL SECURITY;
