CREATE TABLE IF NOT EXISTS desafios (dia_nascimento INTEGER PRIMARY KEY, desafio TEXT, descricao TEXT);
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (1, 'INSUBORDINAÇÃO', 'Recusa em acatar ordens legítimas de autoridade, desafiando ou desobedecendo instruções diretas.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (2, 'PREPOTÊNCIA', 'Atitude marcada pela crença exagerada na própria superioridade e no poder pessoal, levando a desprezo ou dominação dos demais.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (3, 'AGRESSIVIDADE', 'Expressão de sentimentos e opiniões de forma hostil ou ameaçadora, transgredindo direitos de outros para impor vontades34.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (4, 'PESSIMISMO', 'Tendência a antecipar resultados negativos e focar nos aspectos desfavoráveis das situações5.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (5, 'IMPACIÊNCIA', 'Dificuldade em esperar, demonstrando inquietação frente a atrasos ou obstáculos.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (6, 'INDECISÃO', 'Hesitação recorrente entre alternativas, marcada por dificuldade em escolher e agir.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (7, 'CENTRALIZADOR', 'Necessidade recorrente de controlar decisões e processos, evitando delegar tarefas.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (8, 'DESCONFIANÇA', 'Expectativa contínua de intenções negativas ou enganos por parte dos outros.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (9, 'FALTA DE PERSISTÊNCIA', 'Desistência frequente diante de dificuldades, dificuldade em manter esforços prolongados.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (10, 'SUPERIORIDADE', 'Sentimento ou comportamento de se considerar melhor ou mais capaz que os outros.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (11, 'INCONSISTÊNCIA', 'Mudança frequente de opiniões ou comportamentos sem justificativa clara.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (12, 'INCONSEQUENTE', 'Age sem considerar as consequências de seus atos, podendo colocar-se ou outros em risco.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (13, 'ANTI SOCIAL', 'Demonstra comportamentos que evitam ou prejudicam interações sociais positivas.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (14, 'FALTA DE CREDIBILIDADE', 'Dificuldade para inspirar confiança nos outros devido a comportamentos passados ou presentes.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (15, 'EGOCENTRISMO', 'Tendência a focar excessiva e prioritariamente em si mesmo e em seus próprios interesses.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (16, 'ORGULHO', 'Valorização exagerada das próprias qualidades ou feitos, resistindo a admitir erros.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (17, 'EXIBICIONISMO', 'Busca constante de atenção ou aprovação, exibindo comportamentos ou características para impressionar.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (18, 'EXPLOSÃO', 'Reações emocionais intensas e desproporcionais diante de frustrações.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (19, 'ARROGÂNCIA', 'Demonstração de desprezo ou desdém pelos outros, achando-se superior.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (20, 'ALTA SENSIBILIDADE', 'Reatividade emocional elevada frente a estímulos ou críticas.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (21, 'INSTABILIDADE', 'Variações frequentes no humor ou nas atitudes sem motivo aparente.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (22, 'GANÂNCIA', 'Desejo exagerado de obter vantagens ou possuir bens, acima do necessário.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (23, 'DESCONTROLE', 'Dificuldade em conter impulsos ou emoções, agindo impulsivamente.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (24, 'SENSURA', 'Tendência a criticar ou julgar excessivamente comportamentos próprios ou alheios.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (25, 'INSEGURANÇA', 'Sentimento de incapacidade pessoal, medo de não ser aceito ou fracassar.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (26, 'DOMINADOR', 'Busca constante de exercer poder e controle sobre pessoas e situações.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (27, 'INDOLÊNCIA', 'Falta de disposição para agir; tendência à preguiça e apatia.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (28, 'ACOMODADO', 'Aceita situações negativas ou mediocres sem buscar mudanças.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (29, 'EXTREMISTA', 'Defende ou adota posições muito radicais, com pouca abertura ao diálogo.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (30, 'DESPREOCUPAÇÃO', 'Falta de atenção ou responsabilidade com questões importantes.');
INSERT INTO desafios (dia_nascimento, desafio, descricao) VALUES (31, 'IMPOSITIVO', 'Força opiniões ou vontades sobre os outros, mesmo sem consentimento.');
