version: '3.8'

services:
  web:
    build: .
    container_name: mundokan-app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    volumes:
      - ./.streamlit:/app/.streamlit
