version: '3.8'

services:
  web:
    build: .
    container_name: mundokan-app
    restart: always
    environment:
      - PORT=8501
    volumes:
      - ./.streamlit:/app/.streamlit
    labels:
      - traefik.enable=true
      - traefik.http.routers.mundokan-app.rule=Host(`app.mundokan.com.br`)
      - traefik.http.routers.mundokan-app.entrypoints=websecure
      - traefik.http.routers.mundokan-app.tls.certresolver=letsencrypt
      - traefik.http.services.mundokan-app.loadbalancer.server.port=8501
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
