import pandas as pd

df = pd.read_csv('soft_skills.csv', sep=';')

sql = '''CREATE TABLE IF NOT EXISTS soft_skills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT UNIQUE NOT NULL,
    explicacao TEXT,
    modelo_analise TEXT
);

ALTER TABLE soft_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura publica de dicionarios" ON soft_skills FOR SELECT USING (true);

INSERT INTO soft_skills (nome, explicacao, modelo_analise) VALUES
'''

values = []
for _, row in df.iterrows():
    if pd.isna(row['Soft skill']): continue
    nome = str(row['Soft skill']).replace("'", "''")
    exp = str(row['Explicação prática']).replace("'", "''")
    mod = str(row['Modelo de análise em que é aplicada']).replace("'", "''")
    values.append(f"('{nome}', '{exp}', '{mod}')")

sql += ',\n'.join(values) + ';\n'

with open('upload_soft_skills.sql', 'w', encoding='utf-8') as f:
    f.write(sql)
print('SQL gerado com sucesso!')
