
CREATE TABLE IF NOT EXISTS matriz (
    resultado INTEGER PRIMARY KEY,
    motivacao TEXT,
    impressao TEXT,
    expressao TEXT,
    destino TEXT,
    missao TEXT,
    dia_natalicio TEXT,
    talento_oculto TEXT,
    no_psiquico TEXT,
    tendencias_ocultas TEXT,
    resposta_subconsciente TEXT,
    desafios_ciclo TEXT,
    potencialidade_profissional TEXT,
    desafio_aniversario TEXT,
    triangulo TEXT
);

DELETE FROM matriz;
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (1, 'PIONIERISMO', 'LIDER', 'INICIATIVA', 'INOVAÇÃO', 'LIDER', 'LIDER', 'INOVAÇÃO', 'CONVICÇÃO', 'EGOCENTRISMO', 'EGOCENTRISMO', 'EGOCENTRISMO', 'PIONEIRO', 'INSUBORDINAÇÃO', 'INOVAÇÃO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (2, 'COOPERAÇÃO', 'EMPATIA', 'DIPLOMACIA', 'DIPLOMACIA', 'COLABORAÇÃO', 'DIPLOMACIA', 'COLABORAÇÃO', 'EMPATIA', 'SENSÍVEL', 'MENTIRA', 'SENSÍVEL', 'EQUIPE', 'PREPOTÊNCIA', 'SABEDORIA');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (3, 'COMUNICAÇÃO', 'ENTUSIASMO', 'MULTITALENTO', 'CONEXÃO', 'COMUNICAÇÃO', 'POPULAR', 'CRIATIVO', 'AUDÁCIA', 'PRESUNÇÃO', 'INDISCIPLINA', 'SOCIAL', 'ARTISTA', 'AGRESSIVIDADE', 'CRIAÇÃO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (4, 'ORGANIZAÇÃO', 'ESTABILIDADE', 'ORGANIZAÇÃO', 'CONQUISTA', 'DETERMINAÇÃO', 'PERSISTÊNCIA', 'ORGANIZAÇÃO', 'CONSTÂNCIA', 'TEIMOSIA', 'DETALHISTA', 'FALTA DE VONTADE', 'ACABATIVO', 'PESSIMISMO', 'AUTORIDADE');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (5, 'CONEXÃO', 'MAGNETISMO PESSOAL', 'VERSATILIDADE', 'VERSATILIDADE', 'VERSATILIDADE', 'PERSUASÃO', 'VERSATILIDADE', 'VERSATILIDADE', 'SEM LIMITES', 'TENSO', 'SEM LIMITES', 'VENDEDOR', 'IMPACIÊNCIA', 'VERSATILIDADE');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (6, 'HARMONIA', 'HARMONIA', 'SERVIDOR', 'RESPONSABILIDADE', 'SERVIÇO', 'SERVIÇO', 'CUIDADO', 'SERVIÇO', 'PREOCUPAÇÃO', 'SENTIMENTAL', 'AMOROSIDADE', 'DIPLOMACIA', 'INDECISÃO', 'RELACIONAMENTO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (7, 'ANÁLISE', 'SELETIVO', 'ANALISTA', 'SABEDORIA', 'ANALISTA', 'ANÁLISE MENTAL', 'PERFEIÇÃO', 'ANALISTA', 'ADICÇÕES', 'ANTISOCIAL', 'FECHADO', 'ESPECIALISTA', 'CENTRALIZADOR', 'DIRECIONAMENTO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (8, 'PODER', 'PODER', 'EXECUTOR', 'PODER', 'JUSTIÇA', 'ÊXITO MATERIAL', 'VISIONÁRIO', 'DETERMINAÇÃO', 'AVAREZA', 'CONFIANÇA', 'DINHEIRO', 'EMPREENDEDOR', 'DESCONFIANÇA', 'AUTORIDADE');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (9, 'CONSELHEIRO', 'ALTRUÍSTA', 'COLETIVO', 'COLETIVO', 'UNIVERSALIDADE', 'INTELECTUALIDADE', 'CARISMÁTICO', 'CARISMA', 'RENUNCIA', 'DESINTERESSE', NULL, 'COLETIVO', 'FALTA DE PERSISTÊNCIA', 'CONHECIMENTO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (10, NULL, NULL, NULL, NULL, NULL, 'AUTO CONFIANÇA', NULL, NULL, NULL, NULL, 'TODOS', NULL, 'SUPERIORIDADE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (11, 'INTUITIVO', NULL, 'INTUITIVO', 'INSPIRAÇÃO', 'CONSCIÊNCIA', 'VISIONÁRIO', 'DIPLOMACIA', 'INTUITIVO', 'IMPACIENTE', NULL, NULL, 'INFLUENCIADOR', 'INCONSISTÊNCIA', 'DOMINÂNCIA');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (12, NULL, NULL, NULL, NULL, NULL, 'AUTO EXPRESSÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'INCONSEQUENTE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (13, NULL, NULL, NULL, NULL, NULL, 'PERÍCIA', NULL, NULL, NULL, NULL, NULL, NULL, 'ANTI SOCIAL', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (14, NULL, NULL, NULL, NULL, NULL, 'PERSUASÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'FALTA DE CREDIBILIDADE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (15, NULL, NULL, NULL, NULL, NULL, 'MAGNETISMO PESSOAL', NULL, NULL, NULL, NULL, NULL, NULL, 'EGOCENTRISMO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (16, NULL, NULL, NULL, NULL, NULL, 'TRIUNFO', NULL, NULL, NULL, NULL, NULL, NULL, 'ORGULHO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (17, NULL, NULL, NULL, NULL, NULL, 'PERSPICÁCIA', NULL, NULL, NULL, NULL, NULL, NULL, 'EXIBICIONISMO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (18, NULL, NULL, NULL, NULL, NULL, 'PODER MENTAL', NULL, NULL, NULL, NULL, NULL, NULL, 'EXPLOSÃO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (19, NULL, NULL, NULL, NULL, NULL, 'CORAGEM', NULL, NULL, NULL, NULL, NULL, NULL, 'ARROGÂNCIA', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (20, NULL, NULL, NULL, NULL, NULL, 'SENSÍVEL', NULL, NULL, NULL, NULL, NULL, NULL, 'ALTA SENSIBILIDADE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (21, NULL, NULL, NULL, NULL, NULL, 'SUCESSO', NULL, NULL, NULL, NULL, NULL, NULL, 'INSTABILIDADE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (22, 'CONCRETIZAÇÃO', NULL, 'CONSTRUTOR', 'CONSTRUTOR', 'ESPERANÇA', 'RESULTADO', 'RESULTADO', NULL, NULL, NULL, NULL, 'INTUITIVO', 'GANÂNCIA', 'REALIZAÇÃO');
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (23, NULL, NULL, NULL, NULL, NULL, 'PERSUASÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'DESCONTROLE', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (24, NULL, NULL, NULL, NULL, NULL, 'SOLÍCITO', NULL, NULL, NULL, NULL, NULL, NULL, 'SENSURA', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (25, NULL, NULL, NULL, NULL, NULL, 'PROGRESSO', NULL, NULL, NULL, NULL, NULL, NULL, 'INSEGURANÇA', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (26, NULL, NULL, NULL, NULL, NULL, 'JUSTIÇA', NULL, NULL, NULL, NULL, NULL, NULL, 'DOMINADOR', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (27, NULL, NULL, NULL, NULL, NULL, 'AUDÁCIA', NULL, NULL, NULL, NULL, NULL, NULL, 'INDOLÊNCIA', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (28, NULL, NULL, NULL, NULL, NULL, 'VONTADE', NULL, NULL, NULL, NULL, NULL, NULL, 'ACOMODADO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (29, NULL, NULL, NULL, NULL, NULL, 'INTELECTUALIDADE', NULL, NULL, NULL, NULL, NULL, NULL, 'EXTREMISTA', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (30, NULL, NULL, NULL, NULL, NULL, 'REALIZAÇÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'DESPREOCUPAÇÃO', NULL);
INSERT INTO matriz (resultado, motivacao, impressao, expressao, destino, missao, dia_natalicio, talento_oculto, no_psiquico, tendencias_ocultas, resposta_subconsciente, desafios_ciclo, potencialidade_profissional, desafio_aniversario, triangulo) VALUES (31, NULL, NULL, NULL, NULL, NULL, 'HABILIDADE', NULL, NULL, NULL, NULL, NULL, NULL, 'IMPOSITIVO', NULL);
