CREATE TABLE IF NOT EXISTS soft_skills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT UNIQUE NOT NULL,
    explicacao TEXT,
    modelo_analise TEXT
);

-- Habilita RLS por padrão
ALTER TABLE soft_skills ENABLE ROW LEVEL SECURITY;

-- Permite leitura pública (mesmo padrão dos outros dicionários como arcanos, kans)
CREATE POLICY "Permitir leitura publica de dicionarios" ON soft_skills FOR SELECT USING (true);

-- Popula os dados
INSERT INTO soft_skills (nome, explicacao, modelo_analise) VALUES
('Comunicação eficaz', 'Expressar ideias de forma clara e adequada ao público, em fala e escrita.', 'Entrevistas por competências, DISC (perfis de influência), avaliação 360°'),
('Comunicação assertiva', 'Defender ideias com clareza e respeito, sem agressividade ou submissão.', 'Entrevistas comportamentais, DISC (dominância x submissão), role plays'),
('Escuta ativa', 'Ouvir com atenção, fazer perguntas e checar entendimento antes de responder.', 'Entrevistas por competências, assessment centers, feedback 360°'),
('Trabalho em equipe', 'Cooperar, compartilhar informação e buscar objetivos comuns.', 'DISC (cooperação), Big Five (afabilidade), dinâmicas de grupo'),
('Relacionamento interpessoal', 'Criar e manter boas relações, lidar bem com diferentes perfis.', 'Big Five (afabilidade, extroversão), sociogramas de equipe'),
('Empatia', 'Perceber e considerar sentimentos e perspectivas dos outros.', 'Inteligência emocional (EQ-i, MSCEIT), entrevistas comportamentais'),
('Colaboração', 'Trabalhar de forma integrada, ajudando e pedindo ajuda quando necessário.', 'Avaliações de clima/equipe, assessment center, DISC (estabilidade/cooperação)'),
('Liderança', 'Influenciar pessoas, organizar recursos e direcionar o grupo para metas.', 'Inventários de liderança, 9-box, DISC (alta dominância/influência), 360°'),
('Inteligência emocional', 'Reconhecer e administrar emoções próprias e alheias.', 'Testes de IE, entrevistas por competências, feedback 360°'),
('Resiliência', 'Manter o foco e se recuperar depois de fracassos e mudanças.', 'Inventários de coping/resiliência, entrevistas comportamentais'),
('Adaptabilidade / flexibilidade', 'Ajustar-se rápido a mudanças de contexto, prioridades ou processos.', 'Big Five (abertura à experiência), entrevistas de potencial, assessment center'),
('Proatividade', 'Agir antes de ser cobrado, antecipar problemas e propor melhorias.', 'Entrevistas por competências (método STAR), avaliações de desempenho'),
('Organização', 'Planejar tarefas, manter informações em ordem e seguir rotinas.', 'Big Five (conscienciosidade), testes de estilo de trabalho'),
('Gestão do tempo', 'Priorizar tarefas, cumprir prazos e evitar desperdícios de tempo.', 'Ferramentas de produtividade, entrevistas por competências, autoavaliações'),
('Disciplina', 'Manter constância nos hábitos e seguir combinados mesmo sem motivação.', 'Big Five (conscienciosidade), avaliações de desempenho, feedback 360°'),
('Pontualidade', 'Cumprir horários e prazos, demonstrando respeito pelo tempo alheio.', 'Indicadores de desempenho, registros de presença, avaliação de conduta'),
('Atenção / foco', 'Manter concentração e evitar erros por distração.', 'Testes de atenção, avaliações de desempenho, observação em tarefas'),
('Pensamento crítico', 'Analisar informações, questionar suposições e tirar conclusões lógicas.', 'Testes de raciocínio crítico, estudos de caso, assessment center'),
('Resolução de problemas', 'Identificar causas, gerar alternativas e implementar soluções viáveis.', 'Estudos de caso, entrevistas por competências, testes situacionais'),
('Tomada de decisão', 'Escolher caminhos com base em dados, riscos e valores, assumindo responsabilidade.', 'Simulações de negócios, assessment center, entrevistas por competências'),
('Criatividade', 'Gerar ideias novas ou combinar elementos de forma original.', 'Testes de criatividade, dinâmicas de ideação (design thinking), portfólio'),
('Inovação / melhoria contínua', 'Transformar ideias em mudanças reais que geram valor.', 'Programas de inovação interna, OKRs/projetos, entrevistas de potencial'),
('Visão sistêmica', 'Entender como as partes da empresa se conectam e se influenciam.', 'Mapeamento de competências, simulações de negócios, avaliação de liderança'),
('Ética / responsabilidade', 'Agir de forma íntegra, cumprir acordos e respeitar normas e valores.', 'Códigos de conduta, avaliações de cultura/fit, entrevistas de valores'),
('Produtividade', 'Entregar volume e qualidade de trabalho de forma consistente.', 'Avaliações de desempenho, indicadores de KPIs individuais'),
('Aprendizado contínuo', 'Buscar se atualizar, estudar e testar coisas novas ao longo da carreira.', 'Planos de desenvolvimento individual (PDI), 9-box, entrevistas de potencial')
ON CONFLICT (nome) DO UPDATE SET 
    explicacao = EXCLUDED.explicacao,
    modelo_analise = EXCLUDED.modelo_analise;
